# H2 w Linux FS (WSL) – unikasz problemów z /mnt/c
spring.datasource.url=jdbc:h2:file:/tmp/go-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# automatyczne tworzenie/aktualizacja tabel
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# parametry aplikacji
go.mode=server
go.server.port=5001
go.board.size=9
go.replay.gameId=0
